server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gain-Lee/config-repo
          search-paths: licensingservice, organizationservice
          username: Gain-Lee
          password: gee9jae1
management:
  endpoints:
    web:
      exposure:
        include: mappings